# Generated by Django 5.2.5 on 2025-08-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
