# Generated by Django 5.2.5 on 2025-08-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_repayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repayments',
            old_name='loan_id',
            new_name='loan',
        ),
        migrations.RenameField(
            model_name='repayments',
            old_name='user_id',
            new_name='user',
        ),
    ]
