# Generated by Django 5.2.5 on 2025-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_rename_loan_id_repayments_loan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayments',
            name='paid_at',
            field=models.DateField(),
        ),
    ]
