# Generated by Django 5.2.5 on 2025-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_repayments_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayments',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
