# Generated by Django 5.2.5 on 2025-08-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_repayments_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repayments',
            name='user',
        ),
    ]
