# Generated by Django 5.2.5 on 2025-08-20 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_confirm_password_alter_user_password'),
        ('loans', '0006_remove_repayments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
